# Generated by Django 4.2 on 2025-06-04 08:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='cleaning_service')),
                ('icon_img', models.ImageField(blank=True, null=True, upload_to='cleaning_service')),
                ('title1', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
