# Generated by Django 4.2 on 2025-06-04 16:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cleaning_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_left',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='review_left')),
                ('video', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
