# Generated by Django 4.2 on 2025-06-04 17:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_review_left'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
