# Generated by Django 4.2 on 2025-06-04 17:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_img', models.ImageField(blank=True, null=True, upload_to='counter')),
                ('name', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('count', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
