# Generated by Django 4.2 on 2025-06-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning_service1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='cleaning_service')),
                ('icon_img', models.ImageField(blank=True, null=True, upload_to='cleaning_service')),
                ('title1', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
