# Generated by Django 4.2 on 2025-06-05 18:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_blogcategory_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teamaera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teamaera')),
                ('name', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('position', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
