# Generated by Django 4.2 on 2025-06-06 17:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_teamaera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_details')),
                ('name', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('position', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('age', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('phone_num', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('address', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('experience', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='team_detail')),
            ],
        ),
    ]
