# Generated by Django 4.2 on 2025-06-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_team_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_details',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='team_details'),
        ),
    ]
